In [1]:
import polars as pl

In [2]:
df = pl.read_csv(
    "../crispr_search/plasmid_host_taxonomy_consolidated_all_possible_hosts_final_derep.tsv",
    separator="\t",
)

df = df.with_columns(
    phylum=pl.col("host").str.split(";").list.get(1),
    cclass=pl.col("host").str.split(";").list.get(2),
    order=pl.col("host").str.split(";").list.get(3),
    family=pl.col("host").str.split(";").list.get(4),
    genus=pl.col("host").str.split(";").list.get(5),
    species=pl.col("host").str.split(";").list.get(6),
)

df.head()

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Plasmid   ┆ host      ┆ method    ┆ phylum    ┆ … ┆ order     ┆ family    ┆ genus     ┆ species  │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 208809001 ┆ d__Bacter ┆ iphop-bla ┆ p__Pseudo ┆ … ┆ o__Rhizob ┆ f__Methyl ┆ g__Methyl ┆ s__Methy │
│ 4|GPIPI_1 ┆ ia;p__Pse ┆ st        ┆ monadota  ┆   ┆ iales     ┆ oligellac ┆ oceanibac ┆ loceanib │
│ 6557027   ┆ udomonado ┆           ┆           ┆   ┆           ┆ eae       ┆ ter       ┆ acter    │
│           ┆ ta;c_…    ┆           ┆           ┆   ┆           ┆           ┆           ┆ sp003135 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 45…      │
│ 208809001 ┆ d__Bacter ┆ iphop-bla ┆ p__Pseudo ┆ … ┆ o__Rhizob ┆ f__Methyl ┆ g__Methyl ┆ null     │
│ 4|GPIPI_1 ┆ ia;p__Pse ┆ st        ┆ monadota  ┆   ┆ iales     ┆ oligellac ┆ oceanibac ┆          │
│ 6557027   ┆ udomonado ┆           ┆           ┆   ┆           ┆ eae       ┆ ter       ┆          │
│           ┆ ta;c_…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 208809001 ┆ d__Bacter ┆ iphop-bla ┆ p__Acidob ┆ … ┆ o__Vicina ┆ f__UBA299 ┆ g__2-02-F ┆ null     │
│ 4|GPIPI_1 ┆ ia;p__Aci ┆ st        ┆ acteriota ┆   ┆ mibactera ┆ 9         ┆ ULL-65-29 ┆          │
│ 6944593   ┆ dobacteri ┆           ┆           ┆   ┆ les       ┆           ┆           ┆          │
│           ┆ ota;c…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 208809001 ┆ d__Bacter ┆ iphop-bla ┆ p__Acidob ┆ … ┆ o__Vicina ┆ f__UBA299 ┆ g__2-02-F ┆ s__2-02- │
│ 4|GPIPI_1 ┆ ia;p__Aci ┆ st        ┆ acteriota ┆   ┆ mibactera ┆ 9         ┆ ULL-65-29 ┆ FULL-65- │
│ 6944593   ┆ dobacteri ┆           ┆           ┆   ┆ les       ┆           ┆           ┆ 29 sp001 │
│           ┆ ota;c…    ┆           ┆           ┆   ┆           ┆           ┆           ┆ 767435   │
│ 208809001 ┆ d__Bacter ┆ iphop-bla ┆ p__Actino ┆ … ┆ o__Gaiell ┆ f__Gaiell ┆ g__GMQP-b ┆ null     │
│ 5|GPICI_8 ┆ ia;p__Act ┆ st        ┆ mycetota  ┆   ┆ ales      ┆ aceae     ┆ ins7      ┆          │
│ 721071    ┆ inomyceto ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ta;c_…    ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [3]:
isolate_host = df.filter((pl.col("Plasmid").str.contains('IMGPR|PLSDB|Refsoil')) & (pl.col('method')=='isolate')).select(pl.exclude('host','method'))

isolate_host.head()

shape: (5, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ Plasmid      ┆ phylum      ┆ cclass      ┆ order       ┆ family      ┆ genus       ┆ species     │
│ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ str          ┆ str         ┆ str         ┆ str         ┆ str         ┆ str         ┆ str         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ IMGPR_plasmi ┆ p__Proteoba ┆ c__Alphapro ┆ o__Rhizobia ┆ f__Rhizobia ┆ g__Rhizobiu ┆ s__Rhizobiu │
│ d_2228664006 ┆ cteria      ┆ teobacteria ┆ les         ┆ ceae        ┆ m           ┆ m altiplani │
│ _000005      ┆             ┆             ┆             ┆             ┆             ┆             │
│ IMGPR_plasmi ┆ p__Pseudomo ┆ c__Alphapro ┆ o__Rhizobia ┆ f__Rhizobia ┆ g__Rhizobiu ┆ s__Rhizobiu │
│ d_2228664006 ┆ nadota      ┆ teobacteria ┆ les         ┆ ceae        ┆ m           ┆ m altiplani │
│ _000005      ┆             ┆             ┆             ┆             ┆             ┆             │
│ IMGPR_plasmi ┆ p__Proteoba ┆ c__Alphapro ┆ o__Rhizobia ┆ f__Rhizobia ┆ g__Rhizobiu ┆ s__Rhizobiu │
│ d_2228664006 ┆ cteria      ┆ teobacteria ┆ les         ┆ ceae        ┆ m           ┆ m altiplani │
│ _000006      ┆             ┆             ┆             ┆             ┆             ┆             │
│ IMGPR_plasmi ┆ p__Pseudomo ┆ c__Alphapro ┆ o__Rhizobia ┆ f__Rhizobia ┆ g__Rhizobiu ┆ s__Rhizobiu │
│ d_2228664006 ┆ nadota      ┆ teobacteria ┆ les         ┆ ceae        ┆ m           ┆ m altiplani │
│ _000006      ┆             ┆             ┆             ┆             ┆             ┆             │
│ IMGPR_plasmi ┆ p__Pseudomo ┆ c__Alphapro ┆ o__Rhizobia ┆ f__Rhizobia ┆ g__Rhizobiu ┆ s__Rhizobiu │
│ d_2228664006 ┆ nadota      ┆ teobacteria ┆ les         ┆ ceae        ┆ m           ┆ m altiplani │
│ _000008      ┆             ┆             ┆             ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [4]:
df.filter(pl.col("Plasmid").str.contains('IMGPR|PLSDB|Refsoil')).group_by('Plasmid').agg(pl.col('method').n_unique())

shape: (8_081, 2)
┌─────────────────────────────────┬────────┐
│ Plasmid                         ┆ method │
│ ---                             ┆ ---    │
│ str                             ┆ u32    │
╞═════════════════════════════════╪════════╡
│ IMGPR_plasmid_2770939619_000006 ┆ 2      │
│ Refsoil_NC_019898.1             ┆ 1      │
│ IMGPR_plasmid_2915933370_000002 ┆ 2      │
│ IMGPR_plasmid_2901872072_000011 ┆ 2      │
│ …                               ┆ …      │
│ IMGPR_plasmid_2802428818_000007 ┆ 2      │
│ PLSDB_NZ_CP101136.1             ┆ 1      │
│ PLSDB_NZ_CP012864.1             ┆ 1      │
│ IMGPR_plasmid_2754412365_000001 ┆ 2      │
└─────────────────────────────────┴────────┘

In [5]:
iphop_host = df.filter((pl.col("Plasmid").str.contains('IMGPR|PLSDB|Refsoil')) & (pl.col('method').str.contains('iphop'))).select(pl.exclude('host', 'method'))

iphop_host.head()

shape: (5, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ Plasmid      ┆ phylum      ┆ cclass      ┆ order       ┆ family      ┆ genus       ┆ species     │
│ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│ str          ┆ str         ┆ str         ┆ str         ┆ str         ┆ str         ┆ str         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ IMGPR_plasmi ┆ p__Pseudomo ┆ c__Alphapro ┆ o__Rhizobia ┆ f__Rhizobia ┆ g__Rhizobiu ┆ s__Rhizobiu │
│ d_2228664006 ┆ nadota      ┆ teobacteria ┆ les         ┆ ceae        ┆ m           ┆ m tibeticum │
│ _000005      ┆             ┆             ┆             ┆             ┆             ┆             │
│ IMGPR_plasmi ┆ p__Pseudomo ┆ c__Alphapro ┆ o__Rhizobia ┆ f__Rhizobia ┆ g__Rhizobiu ┆ s__Rhizobiu │
│ d_2228664006 ┆ nadota      ┆ teobacteria ┆ les         ┆ ceae        ┆ m           ┆ m           │
│ _000005      ┆             ┆             ┆             ┆             ┆             ┆ sp900466605 │
│ IMGPR_plasmi ┆ p__Pseudomo ┆ c__Alphapro ┆ o__Rhizobia ┆ f__Rhizobia ┆ g__Rhizobiu ┆ s__Rhizobiu │
│ d_2228664006 ┆ nadota      ┆ teobacteria ┆ les         ┆ ceae        ┆ m           ┆ m           │
│ _000005      ┆             ┆             ┆             ┆             ┆             ┆ sp012641395 │
│ IMGPR_plasmi ┆ p__Pseudomo ┆ c__Alphapro ┆ o__Rhizobia ┆ f__Rhizobia ┆ g__Rhizobiu ┆ s__Rhizobiu │
│ d_2228664006 ┆ nadota      ┆ teobacteria ┆ les         ┆ ceae        ┆ m           ┆ m cauense   │
│ _000005      ┆             ┆             ┆             ┆             ┆             ┆             │
│ IMGPR_plasmi ┆ p__Pseudomo ┆ c__Alphapro ┆ o__Rhizobia ┆ f__Rhizobia ┆ g__Rhizobiu ┆ null        │
│ d_2228664006 ┆ nadota      ┆ teobacteria ┆ les         ┆ ceae        ┆ m           ┆             │
│ _000005      ┆             ┆             ┆             ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [7]:
iphop_host.select(pl.col('Plasmid')).unique()

shape: (5_294, 1)
┌─────────────────────────────────┐
│ Plasmid                         │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ IMGPR_plasmid_2765236068_000003 │
│ IMGPR_plasmid_2721755522_000001 │
│ IMGPR_plasmid_2806310628_000002 │
│ IMGPR_plasmid_2808606945_000002 │
│ …                               │
│ IMGPR_plasmid_2744054626_000024 │
│ IMGPR_plasmid_2537562008_000009 │
│ IMGPR_plasmid_2778260928_000001 │
│ IMGPR_plasmid_2617270932_000007 │
└─────────────────────────────────┘

In [6]:
a = isolate_host.join(iphop_host, on='Plasmid', how='left').with_columns(species_agreement=pl.when(pl.col('species')==pl.col('species_right')).then(True).otherwise(False),
genus_agreement=pl.when(pl.col('genus')==pl.col('genus_right')).then(True).otherwise(False),
family_agreement=pl.when(pl.col('family')==pl.col('family_right')).then(True).otherwise(False),
order_agreement=pl.when(pl.col('order')==pl.col('order_right')).then(True).otherwise(False),
cclass_agreement=pl.when(pl.col('cclass')==pl.col('cclass_right')).then(True).otherwise(False),
phylum_agreement=pl.when(pl.col('phylum')==pl.col('phylum_right')).then(True).otherwise(False),
).filter(pl.col('phylum_right').is_not_null()).group_by('Plasmid').agg(pl.col('species_agreement').any().alias('species_agreement'), pl.col('genus_agreement').any().alias('genus_agreement'),
pl.col('family_agreement').any().alias('family_agreement'), pl.col('order_agreement').any().alias('order_agreement'),
pl.col('cclass_agreement').any().alias('cclass_agreement'), pl.col('phylum_agreement').any().alias('phylum_agreement'))

a.head()

shape: (5, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ Plasmid      ┆ species_agr ┆ genus_agree ┆ family_agre ┆ order_agree ┆ cclass_agre ┆ phylum_agre │
│ ---          ┆ eement      ┆ ment        ┆ ement       ┆ ment        ┆ ement       ┆ ement       │
│ str          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│              ┆ bool        ┆ bool        ┆ bool        ┆ bool        ┆ bool        ┆ bool        │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ IMGPR_plasmi ┆ false       ┆ false       ┆ true        ┆ true        ┆ true        ┆ true        │
│ d_2899663056 ┆             ┆             ┆             ┆             ┆             ┆             │
│ _000007      ┆             ┆             ┆             ┆             ┆             ┆             │
│ IMGPR_plasmi ┆ false       ┆ true        ┆ true        ┆ true        ┆ true        ┆ true        │
│ d_2791355089 ┆             ┆             ┆             ┆             ┆             ┆             │
│ _000011      ┆             ┆             ┆             ┆             ┆             ┆             │
│ IMGPR_plasmi ┆ true        ┆ true        ┆ true        ┆ true        ┆ true        ┆ true        │
│ d_2636415960 ┆             ┆             ┆             ┆             ┆             ┆             │
│ _000001      ┆             ┆             ┆             ┆             ┆             ┆             │
│ IMGPR_plasmi ┆ false       ┆ true        ┆ true        ┆ true        ┆ true        ┆ true        │
│ d_2858317900 ┆             ┆             ┆             ┆             ┆             ┆             │
│ _000009      ┆             ┆             ┆             ┆             ┆             ┆             │
│ IMGPR_plasmi ┆ true        ┆ true        ┆ true        ┆ true        ┆ true        ┆ true        │
│ d_2903953040 ┆             ┆             ┆             ┆             ┆             ┆             │
│ _000048      ┆             ┆             ┆             ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [10]:
a.select(pl.col('species_agreement').sum()/ a.shape[0], pl.col('genus_agreement').sum()/ a.shape[0], pl.col('family_agreement').sum()/ a.shape[0], pl.col('order_agreement').sum()/ a.shape[0], pl.col('cclass_agreement').sum()/ a.shape[0], pl.col('phylum_agreement').sum()/ a.shape[0])

shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ species_agreem ┆ genus_agreemen ┆ family_agreeme ┆ order_agreeme ┆ cclass_agreem ┆ phylum_agreem │
│ ent            ┆ t              ┆ nt             ┆ nt            ┆ ent           ┆ ent           │
│ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---           ┆ ---           │
│ f64            ┆ f64            ┆ f64            ┆ f64           ┆ f64           ┆ f64           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ 0.429327       ┆ 0.909108       ┆ 0.97449        ┆ 0.966931      ┆ 0.992819      ┆ 0.780045      │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘